language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - nightly
  - pypy3

install:
  - if [[ $TRAVIS_PYTHON_VERSION < '3.4' ]]; then pip install enum34; fi
  - pip install pyserial pillow
  - python setup.py install

script: py.test --port=/dev/pts/1

matrix:
    fast_finish: true
